site_name: Knowledge Based
site_url: https://it.unity.sch.id
site_description: Knowledge Base
site_author:  Tim

theme:
  name: mkdocs
  custom_dir: overrides
  locale: id
  nav_style: dark
  color_mode: auto
  user_color_mode_toggle: false

markdown_extensions:

  - admonition

  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.tabbed:
      alternate_style: true

  - attr_list

  - md_in_html

  - toc:
      permalink: true

plugins:

  - search:
      lang:
        - en

extra_css:
  - stylesheets/extra.css

nav:

  - Home: index.md

  # - Getting Started:
  #     - Introduction: getting-started/index.md

  - Hardisk:
      - Hard Disk dan Penyimpanan: hardisk/index.md
      - BIOS Tidak Mendeteksi Hard Drive: hardisk/bios-not-detecting-drive/index.md

  - Windows:
      - Memasang Driver yang Hilang: drivers/index.md
      - Memperbaiki Windows Boot Loop: windows/boot-loop/index.md
      - Membuat Windows 11 Lebih Lancar: windows/performance/index.md
      - Troubleshooting Proyektor: projector/index.md

  - Printer:
      - Komputer Tidak Bisa Print: printer/index.md

  - Jaringan Internet:
      - Internet LAN Tidak Muncul: network/lan-internet/index.md
      - Troubleshooting Internet Kabel LAN: network/troubleshooting-lan/index.md
      - Cara Merestart Access Point: network/restart-tp-link-tl-wr940n/index.md
