site_name: IT Knowledge Base
site_url: https://it.unity.sch.id
site_description: IT Documentation & Knowledge Base
site_author:  IT Department

theme:
  name: mkdocs
  custom_dir: overrides
  locale: id
  nav_style: dark
  color_mode: auto
  user_color_mode_toggle: false

markdown_extensions:

  - admonition

  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.tabbed:
      alternate_style: true

  - attr_list

  - md_in_html

  - toc:
      permalink: true

plugins:

  - search:
      lang:
        - en

extra_css:
  - stylesheets/extra.css

nav:

  - Home: index.md

  # - Getting Started:
  #     - Introduction: getting-started/index.md

  - Hardisk:
      - Hard Disk dan Penyimpanan: hardisk/index.md
